### PR TITLE
IDEX-4041: Memory leak in static maps in java debugger

### PR DESCRIPTION
**Pull request by tolusha**

### CODE REVIEW

**Comment by tolusha** [comment]
@vparfonov 
@skabashnyuk

**Comment by tolusha** [comment]
The idea of the patch:
since we caught disconnect event no need to perform disconnect again. Exception occurs and Debugger instance remains in map.

**Comment by vparfonov** [comment]
+1

**Comment by skabashnyuk** [comment]
ok

**Pull request merged**
