### PR TITLE
IDEX-3472 Use of Docker0 bridge name when we're on linux (bridge0 was not for Linux)

### PR DESCRIPTION
**Pull request by benoitf**
(see http://docs.docker.com/v1.8/articles/networking/) 
Change-Id: I6264bfcf93221a54f70079ff868cc4eccabcbd52
Signed-off-by: Florent BENOIT <fbenoit@codenvy.com>

### CODE REVIEW

**Comment by skabashnyuk** [comment]
+0 Have you checked on Linux?

**Comment by benoitf** [comment]
well bridge0 was not the expected name when I've done the work.
Bridge name has to be 'docker0' so I'm pretty sure that today it doesn't work.(it use fallback ip for now)

**Comment by garagatyi** [comment]
I think some guys already said that it is not working on Linux. On my machine bridge name is `docker0`. In devbox installation it is the same

**Comment by garagatyi** [comment]
LGTM

**Comment by garagatyi** [comment]
https://jira.codenvycorp.com/browse/IDEX-3472

**Pull request merged**
