### PR TITLE
IDEX-3333 - adding README with drag&drop button

### PR DESCRIPTION
**Pull request by stour**
Adding a button for plugins that are not packaged by default with Che and that contain only one JAR.
(plugin-angularjs contains several JAR but is already packaged as che-plugin so button uses angularjs-assembly ZIP)

### CODE REVIEW

**Comment by skabashnyuk** [comment]
LGTM

**Comment by stour** [comment]
@benoitf just informed me that we are now able to use CURRENT as version in drag&drop button so I will update this PR accordingly

**Comment by riuvshin** [comment]
@benoitf @stour this is awesome! thank you guys!

**Comment by stour** [comment]
@skabashnyuk @vparfonov PR is now ready for merging
should I squash the two commits ?

**Comment by benoitf** [comment]
I think it should be better to squash these two commits

**Comment by stour** [comment]
done

**Pull request merged**
