### PR TITLE
IDEX-3887: Do not block IDE when debugger is connecting to remote server

### PR DESCRIPTION
**Pull request by vinokurig**
@skabashnyuk @vparfonov @tolusha please review

### CODE REVIEW

**Comment by tolusha** [comment]
ok

**Comment by skabashnyuk** [comment]
Can you update your PR with current sources?

**Comment by vparfonov** [comment]
ok

**Comment by skabashnyuk** [comment]
Current state is NOT ok

**Comment by vinokurig** [comment]
updated with master, resolved conflicts

**Comment by skabashnyuk** [comment]
щл

**Pull request merged**
