### PR TITLE
IDEX-4010 Add injection of user's ssh public keys

### PR DESCRIPTION
**Pull request by sleshchenko**
@skabashnyuk @garagatyi

### CODE REVIEW

**Comment by garagatyi** [comment]
@vparfonov @evidolob WDYT?

**Comment by garagatyi** [comment]
Maybe it would be better to replace docker exec with machine process, [e.g.](https://github.com/codenvy/che-core/blob/master/platform-api/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/WsAgentLauncherImpl.java) ? WDYT

**Comment by sleshchenko** [comment]
I think In my case docker exec is more simple.

**Comment by garagatyi** [comment]
ok
@skabashnyuk WDYT?

**Comment by skabashnyuk** [comment]
ok

**Comment by vparfonov** [comment]
ok

**Pull request merged**
