### PR TITLE
IDEX-2389: Add getProjectExplorerSelection method in SelectionAgent

### PR DESCRIPTION
**Pull request by vinokurig**
When performing git commit with "add selected files" check-box selected and console part is active, NPE appears because the getSelection method in Selection agent returned a selection of console part, but we need a selection of project explorer
@vparfonov @skabashnyuk  please review

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ok for me. @vparfonov ?

**Comment by azatsarynnyy** [comment]
see https://github.com/codenvy/che-core/pull/660#issuecomment-173586576

**Comment by vinokurig** [comment]
Used Project explorer presenter instead of Selection agent

**Comment by vparfonov** [comment]
ok

**Pull request merged**
